<?php

  /***********************************************************************************
    BONES
   **********************************************************************************/

  require_once( 'lib/inc/bones.php' );





  /***********************************************************************************
    PLUGINS / LIBS / CLASSES
   **********************************************************************************/

  require_once( 'lib/inc/plugins/cpt-in-navmenu/cpt-in-navmenu.php' );





  /***********************************************************************************
    CUSTOM POST TYPES
   **********************************************************************************/

  require_once( 'lib/inc/post-types/product.php' );





  /***********************************************************************************
    MENUS
   **********************************************************************************/

  register_nav_menus(
    array(
      'main-nav' => __('The Main Menu', 'boilerplate_theme')
    )
  );





  /***********************************************************************************
    IMAGE SIZES
   **********************************************************************************/

  /**
    500 x 500px hard cropped.
   */
  add_image_size( '500x500', 500, 500, true );

  /**
    Width hard cropped to 1000px, height can be anything.
   */
  add_image_size( 'custom-size', 1000 );





  /***********************************************************************************
    SCRIPTS / STYLES
   **********************************************************************************/

  if ( ! is_admin() ) {

    wp_enqueue_style('primary', get_template_directory_uri() . '/lib/css/style.min.css');

    wp_enqueue_style('secondary', get_stylesheet_uri(), array('primary'));

    wp_enqueue_script('jquery');

    wp_enqueue_script('main', get_template_directory_uri() . '/lib/js/main.min.js', array('jquery'), false, true);

  }





  /***********************************************************************************
    VARIOUS
   **********************************************************************************/

  /**
    Remove HTML whitespace.
   */
  function remove_html_whitespace ( $html ) {
    return preg_replace( '~>\s+<~', '><', $html );
  }


  /**
    `/?s=` to `/search/` in URLs.
   */

  function change_search_url_rewrite() {
    if ( is_search() && ! empty( $_GET['s'] ) ) {
      wp_redirect( home_url( '/search/') . urlencode( get_query_var( 's' ) ) );
      exit();
    }
  }
  add_action('template_redirect', 'change_search_url_rewrite');


  /**
    Get permalink by using the slug as reference.
   */
  function get_permalink_by_slug ( $slug, $post_type = '' ) {
    $permalink = null;
    $args = array(
      'name' => $slug,
      'max_num_posts' => 1
    );
    if ( '' != $post_type ) {
      $args = array_merge( $args, array( 'post_type' => $post_type ) );
    }
    $query = new WP_Query( $args );
    if ( $query->have_posts() ) {
      $query->the_post();
      $permalink = get_permalink( get_the_ID() );
    }
    wp_reset_postdata();
    return $permalink;
  }


  /**
    Remove `width` and `height` attributes from post thumbnail `img` elements.
   */
  function remove_thumb_size_attribute ( $html ) {
    $html = preg_replace( '/(width|height)="\d*"\s/', '', $html );
    return $html;
  }
  add_filter( 'post_thumbnail_html', 'remove_thumb_size_attribute', 10 );
  add_filter( 'image_send_to_editor', 'remove_thumb_size_attribute', 10 );


  /**
    Add class to `a` element generated by `previous_posts_link`.
   */
  function pagination_class_prev () {
    return 'class=""';
  }
  add_filter( 'previous_posts_link_attributes', 'pagination_class_prev' );


  /**
    Add class to `a` element generated by `next_posts_link`.
   */
  function pagination_class_next () {
    return 'class=""';
  }
  add_filter( 'next_posts_link_attributes', 'pagination_class_next' );